########################################
# TomCat
server:
  port: 65530


spring:
  # SERVLET
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MVC
  mvc:
    throw-exception-if-no-handler-found: true
