grpc:
  enabled: true
  port: 6565

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:8066/druid?useUnicode=true&CharSet=utf8mb4&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: druid
    password: druid
    # 使用alibaba的druid连接池、监控
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      max-active: 10
      max-wait: 5000
      min-idle: 5
      initial-size: 2
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      web-stat-filter:
        enabled: true
        exclusions: js,gif,jpg,png,css,ico,/druid/*
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid@2019
  jpa:
    hibernate:
      ddlAuto: update
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true

server:
  port: 8080
#mybatis:
#  config-location: classpath:mybatis-config.xml